[package]
name = "aws-oxide-api-route"
version = "0.1.0"
authors = ["jspaulsen <jpaulsen@lo3energy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netlify_lambda_http = "0.1.2"

